name: MSYS2
on: push

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: true
          update: true
          install: zip git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-mbedtls mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-ntldd-git
      - name: Build
        run: |
          python3 build.py
      - name: Deploy
        run: |
          mkdir dist
          for ff in $(${MSYSTEM_PREFIX}/bin/ntldd -R build/ransomwarePOC.exe  | tr '\\' '/' | grep -io "$(cygpath -m ${MSYSTEM_PREFIX}).\+\.dll" | sort -u); do
            cp $(cygpath -u "$ff") dist/
          done
          cp build/ransomwarePOC.exe dist/ransomwarePOC.exe
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: warn